export const landingSlides = [
  { id: "hair-salon-environment", categoryKey: "hair", titleEn: "Luxury Hair Salons in Japan", titleJa: "日本各地のラグジュアリー美容室", subtitleEn: "Discover premium hair salons and barbers for clean cuts, color, and styling.", subtitleJa: "カット・カラー・スタイリングに特化した上質な美容室・理容室をご紹介します。", layoutHint: "left-caption", imageStyle: "environment", priority: 1 },
  { id: "hair-salon-action", categoryKey: "hair", titleEn: "Haircuts and Styling, Done for You", titleJa: "プロの技でヘアカット＆スタイリング", subtitleEn: "See stylists in action — only hands and hair, no faces.", subtitleJa: "手元とヘアスタイルにフォーカスした上品な施術写真（顔は写さない）。", layoutHint: "right-caption", imageStyle: "action", priority: 2 },
  { id: "nail-salon-environment", categoryKey: "nails", titleEn: "Beautiful Nail Studios", titleJa: "洗練されたネイルサロン", subtitleEn: "Minimal, bright interiors perfect for manicures.", subtitleJa: "明るくミニマルなネイルサロン。", layoutHint: "right-caption", imageStyle: "environment", priority: 3 },
  { id: "nail-salon-action", categoryKey: "nails", titleEn: "Detailed Nail Art", titleJa: "細部まで美しいネイルアート", subtitleEn: "Close-up hands receiving a manicure — no faces.", subtitleJa: "施術中の手元クローズアップ（顔は写さない）。", layoutHint: "left-caption", imageStyle: "action", priority: 4 },
  { id: "eyelash-environment", categoryKey: "eyelash", titleEn: "Soft Eyelash Salons", titleJa: "やわらかな雰囲気のまつエクサロン", subtitleEn: "Pastel tones, soft lighting.", subtitleJa: "パステル調の落ち着いた雰囲気。", layoutHint: "left-caption", imageStyle: "environment", priority: 5 },
  { id: "eyelash-action", categoryKey: "eyelash", titleEn: "Natural Eyelash Extensions", titleJa: "自然で美しいまつ毛エクステ", subtitleEn: "Hands & tools only.", subtitleJa: "手元とツールのみ。", layoutHint: "right-caption", imageStyle: "action", priority: 6 },
  { id: "spa-environment", categoryKey: "spa", titleEn: "Relaxing Spas", titleJa: "極上のスパ", subtitleEn: "Warm interiors and premium rooms.", subtitleJa: "落ち着いたスパ空間。", layoutHint: "right-caption", imageStyle: "environment", priority: 7 },
  { id: "spa-action", categoryKey: "spa", titleEn: "Massage and Body Care", titleJa: "マッサージ＆ボディケア", subtitleEn: "Back/shoulder massage (hands only).", subtitleJa: "手元だけのマッサージ写真。", layoutHint: "left-caption", imageStyle: "action", priority: 8 },
  { id: "hotel-environment", categoryKey: "hotel", titleEn: "Luxury Hotels & Ryokan", titleJa: "ラグジュアリーホテル＆旅館", subtitleEn: "Rooms with skyline or Japanese decor.", subtitleJa: "夜景・和室の高級ホテル。", layoutHint: "left-caption", imageStyle: "environment", priority: 9 },
  { id: "hotel-action", categoryKey: "hotel", titleEn: "Stay with a View", titleJa: "景色を楽しむ滞在", subtitleEn: "Hands opening curtains, etc.", subtitleJa: "カーテンを開ける手元。", layoutHint: "right-caption", imageStyle: "action", priority: 10 },
  { id: "restaurant-environment", categoryKey: "restaurant", titleEn: "Fine Dining & Izakaya", titleJa: "レストラン＆居酒屋", subtitleEn: "Cozy interiors.", subtitleJa: "雰囲気のある店内。", layoutHint: "right-caption", imageStyle: "environment", priority: 11 },
  { id: "restaurant-action", categoryKey: "restaurant", titleEn: "Beautiful Food Moments", titleJa: "美しく盛り付けられた料理", subtitleEn: "Chef plating dishes (hands only).", subtitleJa: "手元だけの盛り付け。", layoutHint: "left-caption", imageStyle: "action", priority: 12 },
  { id: "onsen-environment", categoryKey: "onsen", titleEn: "Peaceful Onsens", titleJa: "静かな温泉", subtitleEn: "Outdoor wooden baths.", subtitleJa: "木の露天風呂。", layoutHint: "left-caption", imageStyle: "environment", priority: 13 },
  { id: "onsen-action", categoryKey: "onsen", titleEn: "Hot Spring Moments", titleJa: "温泉を楽しむひととき", subtitleEn: "Ripples / pouring water.", subtitleJa: "お湯の波紋・注ぐ様子。", layoutHint: "right-caption", imageStyle: "action", priority: 14 },
  { id: "clinic-environment", categoryKey: "clinic", titleEn: "Aesthetic Clinics", titleJa: "美容クリニック", subtitleEn: "Clean, bright treatment rooms.", subtitleJa: "明るく清潔な施術室。", layoutHint: "right-caption", imageStyle: "environment", priority: 15 },
  { id: "clinic-action", categoryKey: "clinic", titleEn: "Professional Care", titleJa: "プロの丁寧なケア", subtitleEn: "Hands preparing treatment.", subtitleJa: "施術準備の手元。", layoutHint: "left-caption", imageStyle: "action", priority: 16 }
];

